### ISSUE TITLE
Update action to use Node.js 20

### ISSUE THREAD

**Issue by macox** [port-labs/port-github-action#100]
When using this action the following warning message appears

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: port-labs/port-github-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

**Comment by yairsimantov20** [comment]
Hi thank you for letting us know
We will make sure to take care of it

**Comment by igorbrites** [comment]
Are you guys going to point v1 tag to the latest one, with this node change?

**Comment by OmriGez** [comment]
Hi @igorbrites 
We have released an update to the v1 tag to point to the latest release, which is using Node.js version 20.
Thanks for the heads up.
