### ISSUE TITLE
Tag v1 is not pointing to the latest version tag

### ISSUE THREAD

**Issue by yakirm-cr** [port-labs/port-github-action#119]
Tag `v1` is pointing to tag `v1.6.0` released on 14-Jan-2024.
Unless I am missing something, the tag should point to the (currently) latest version tag `v1.7.0` released on 28-Apr-2024:

![image](https://github.com/port-labs/port-github-action/assets/86773995/7e026f83-46d2-4076-8962-14a97f70f759)

**Comment by OmriGez** [comment]
Hi @yakirm-cr 
We have updated the tag to use the latest release.
Thank you for raising this.
